// projects/betterTasks/frontend/src/lib/components/Navbar.svelte
<script lang="ts">
	import { auth } from '$lib/stores/auth';
	import { tasks } from '$lib/stores/tasks';
	import { goto } from '$app/navigation';

	function handleLogout() {
		auth.logout();
		tasks.clear();
		goto('/');
	}
</script>

<nav class="border-b border-[var(--border)] bg-[var(--bg-secondary)]">
	<div class="max-w-6xl mx-auto px-4 py-4 flex items-center justify-between">
		<h1 class="text-xl font-semibold tracking-tight">betterTasks</h1>
		{#if $auth.user}
			<div class="flex items-center gap-4">
				<span class="text-sm text-[var(--text-secondary)]">{$auth.user.email}</span>
				<button onclick={handleLogout} class="btn-secondary text-sm">Logout</button>
			</div>
		{/if}
	</div>
</nav>

// backend/01-mernNotesApp/frontend/src/components/Navbar.jsx
import { Link } from "react-router";
import { PlusIcon } from "lucide-react";

const Navbar = () => {
	return (
		<header className="bg-base-300 border-b border-base-content/10">
			<div className="mx-auto max-w-6xl p-4">
				<div className="flex justify-between items-center">
					<h1 className="text-3xl font-bold text-primary font-mono tracking-tighter">
						mernNotes
					</h1>
					<div className="flex items-center gap-4">
						<Link to={"/create"} className="btn btn-primary">
							<PlusIcon className="size-5" />
							<span>New Note</span>
						</Link>
					</div>
				</div>
			</div>
		</header>
	);
};

export default Navbar;
